export const serviceOptions = [
  { value: "Select", label: "Select" },
  { value: "Home removals", label: "Home removals" },
  { value: "Office removals", label: "Office removals" },
  { value: "Man and van", label: "Man and van" },
  { value: "Studio flat", label: "Studio flat" },
  { value: "1 Bed property", label: "1 Bed property" },
  { value: "2 Bed property", label: "2 Bed property" },
  { value: "3 Bed property", label: "3 Bed property" },
  { value: "4 Bed property", label: "4 Bed property" },
  { value: "Furniture & Appliances", label: "Furniture & Appliances" },
  { value: "Storage", label: "Storage" },
  //   { value: 'slate', label: 'Slate', color: '#253858' },
  //   { value: 'silver', label: 'Silver', color: '#666666' },
];

export const roleOptions = [
  // { value: "Select", label: "Select" },
  { value: "School Owner", label: "School Owner" },
  { value: "Director", label: "Director" },
  { value: "Principal / Head Teacher", label: "Principal / Head Teacher" },
  { value: "ICT Admin", label: "ICT Admin" },
  { value: "Teacher", label: "Teacher" },
  { value: "Others", label: "Others" },
];

export const paymentPlan = [
  // { value: "Select", label: "Select" },
  { value: "School Owner", label: "School Owner", id: "1" },
  { value: "Director", label: "Director", id: "2" },
  { value: "Principal / Head Teacher", label: "Principal / Head Teacher", id: "3" },
  { value: "ICT Admin", label: "ICT Admin", id: "4" },
  { value: "Teacher", label: "Teacher" },
  { value: "Others", label: "Others" },
];

export const serviceOptions2 = [
  { value: "Select", label: "Select" },
  { value: "1 Bed property", label: "1 Bed property" },
  { value: "2 Bed property", label: "2 Bed property" },
  { value: "3 Bed property", label: "3 Bed property" },
  { value: "4 Bed property", label: "4 Bed property" },
];

export const serviceOptions3 = [
  { value: "Select", label: "Select" },
  { value: "Man and van", label: "Man and van" },
  { value: "Office removals", label: "Office removals" },
  { value: "Studio flat", label: "Studio flat" },
  { value: "Furniture & Appliances", label: "Furniture & Appliances" },
];

export const citiesOptions = [
  { value: "london", label: "London" },
  { value: "birmingham", label: "Birmingham" },
  { value: "manchester", label: "Manchester" },
  { value: "liverpool", label: "Liverpool" },
  { value: "bristol", label: "Bristol" },
  { value: "leeds", label: "Leeds" },
  { value: "newcastle", label: "Newcastle" },
  { value: "sheffield", label: "Sheffield" },
  { value: "nottingham", label: "Nottingham" },
  { value: "southampton", label: "Southampton" },
  { value: "norwich", label: "Norwich" },
  { value: "cardiff", label: "Cardiff" },
  { value: "cambridge", label: "Cambridge" },
  { value: "oxford", label: "Oxford" },
  { value: "brighton", label: "Brighton" },
  { value: "plymouth", label: "Plymouth" },
  { value: "portsmouth", label: "Portsmouth" },
  { value: "leicester", label: "Leicester" },
  { value: "coventry", label: "Coventry" },
  { value: "york", label: "York" },
  { value: "hull", label: "Hull" },
  { value: "bradford", label: "Bradford" },
  { value: "stoke-on-trent", label: "Stoke-on-Trent" },
  { value: "wolverhampton", label: "Wolverhampton" },
  { value: "derby", label: "Derby" },
  { value: "swansea", label: "Swansea" },
  { value: "southend-on-sea", label: "Southend-on-Sea" },
  { value: "sunderland", label: "Sunderland" },
  { value: "nottingham", label: "Nottingham" },
  { value: "luton", label: "Luton" },
  { value: "preston", label: "Preston" },
  { value: "blackpool", label: "Blackpool" },
  { value: "reading", label: "Reading" },
  { value: "northampton", label: "Northampton" },
  { value: "middlesbrough", label: "Middlesbrough" },
  { value: "peterborough", label: "Peterborough" },
  { value: "bournemouth", label: "Bournemouth" },
  { value: "stockport", label: "Stockport" },
  { value: "ipswich", label: "Ipswich" },
  { value: "sunderland", label: "Sunderland" },
  { value: "oxford", label: "Oxford" },
  { value: "bristol", label: "Bristol" },
  { value: "swindon", label: "Swindon" },
  { value: "huddersfield", label: "Huddersfield" },
  { value: "glasgow", label: "Glasgow" },
  { value: "edinburgh", label: "Edinburgh" },
  { value: "dundee", label: "Dundee" },
];

export const menOptions = [
  { value: "Select", label: "Select" },
  { value: "1 Man", label: "1 Man" },
  { value: "2 Men", label: "2 Men" },
  { value: "3 Men", label: "3 Men" },
];

export const mileageOptions = [
  { value: "Select", label: "Select" },
  { value: "0 - 25", label: "0 - 25" },
  { value: "26 - 75", label: "26 - 75" },
  { value: "76 - 150", label: "76 - 150" },
  { value: "151 - 200", label: "151 - 200" },
  { value: "201 - 250", label: "201 - 250" },
  { value: "251 - 300", label: "251 - 300" },
  { value: "301 - 350", label: "301 - 350" },
  { value: "351 - 400", label: "351 - 400" },
  { value: "401 - 450", label: "401 - 450" },
  { value: "451 - 500", label: "451 - 500" },
  { value: "501 - 550", label: "501 - 550" },
  { value: "551 - 600", label: "551 - 600" },
];

export const phoneCodesOptions = [
  { value: "Afghanistan (+93)", label: "Afghanistan (+93)" },
  { value: "Albania (+355)", label: "Albania (+355)" },
  { value: "Algeria (+213)", label: "Algeria (+213)" },
  { value: "American Samoa (+1 684)", label: "American Samoa (+1 684)" },
  { value: "Andorra (+376)", label: "Andorra (+376)" },
  { value: "Angola (+244)", label: "Angola (+244)" },
  { value: "Anguilla (+1 264)", label: "Anguilla (+1 264)" },
  { value: "Antarctica (+672)", label: "Antarctica (+672)" },
  {
    value: "Antigua and Barbuda (+1 268)",
    label: "Antigua and Barbuda (+1 268)",
  },
  { value: "Argentina (+54)", label: "Argentina (+54)" },
  { value: "Armenia (+374)", label: "Armenia (+374)" },
  { value: "Aruba (+297)", label: "Aruba (+297)" },
  { value: "Australia (+61)", label: "Australia (+61)" },
  { value: "Austria (+43)", label: "Austria (+43)" },
  { value: "Azerbaijan (+994)", label: "Azerbaijan (+994)" },
  { value: "Bahamas (+1 242)", label: "Bahamas (+1 242)" },
  { value: "Bahrain (+973)", label: "Bahrain (+973)" },
  { value: "Bangladesh (+880)", label: "Bangladesh (+880)" },
  { value: "Barbados (+1 246)", label: "Barbados (+1 246)" },
  { value: "Belarus (+375)", label: "Belarus (+375)" },
  { value: "Belgium (+32)", label: "Belgium (+32)" },
  { value: "Belize (+501)", label: "Belize (+501)" },
  { value: "Benin (+229)", label: "Benin (+229)" },
  { value: "Bermuda (+1 441)", label: "Bermuda (+1 441)" },
  { value: "Bhutan (+975)", label: "Bhutan (+975)" },
  { value: "Bolivia (+591)", label: "Bolivia (+591)" },
  {
    value: "Bosnia and Herzegovina (+387)",
    label: "Bosnia and Herzegovina (+387)",
  },
  { value: "Botswana (+267)", label: "Botswana (+267)" },
  { value: "Brazil (+55)", label: "Brazil (+55)" },
  {
    value: "British Indian Ocean Territory (+246)",
    label: "British Indian Ocean Territory (+246)",
  },
  {
    value: "British Virgin Islands (+1 284)",
    label: "British Virgin Islands (+1 284)",
  },
  { value: "Brunei (+673)", label: "Brunei (+673)" },
  { value: "Bulgaria (+359)", label: "Bulgaria (+359)" },
  { value: "Burkina Faso (+226)", label: "Burkina Faso (+226)" },
  { value: "Burundi (+257)", label: "Burundi (+257)" },
  { value: "Cambodia (+855)", label: "Cambodia (+855)" },
  { value: "Cameroon (+237)", label: "Cameroon (+237)" },
  { value: "Canada (+1)", label: "Canada (+1)" },
  { value: "Cape Verde (+238)", label: "Cape Verde (+238)" },
  {
    value: "Caribbean Netherlands (+599)",
    label: "Caribbean Netherlands (+599)",
  },
  { value: "Cayman Islands (+1 345)", label: "Cayman Islands (+1 345)" },
  {
    value: "Central African Republic (+236)",
    label: "Central African Republic (+236)",
  },
  { value: "Chad (+235)", label: "Chad (+235)" },
  { value: "Chile (+56)", label: "Chile (+56)" },
  { value: "China (+86)", label: "China (+86)" },
  { value: "Christmas Island (+61)", label: "Christmas Island (+61)" },
  {
    value: "Cocos (Keeling) Islands (+61)",
    label: "Cocos (Keeling) Islands (+61)",
  },
  { value: "Colombia (+57)", label: "Colombia (+57)" },
  { value: "Comoros (+269)", label: "Comoros (+269)" },
  { value: "Congo (DRC) (+243)", label: "Congo (DRC) (+243)" },
  { value: "Congo (Republic) (+242)", label: "Congo (Republic) (+242)" },
  { value: "Cook Islands (+682)", label: "Cook Islands (+682)" },
  { value: "Costa Rica (+506)", label: "Costa Rica (+506)" },
  { value: "Côte d'Ivoire (+225)", label: "Côte d'Ivoire (+225)" },
  { value: "Croatia (+385)", label: "Croatia (+385)" },
  { value: "Cuba (+53)", label: "Cuba (+53)" },
  { value: "Curaçao (+599)", label: "Curaçao (+599)" },
  { value: "Cyprus (+357)", label: "Cyprus (+357)" },
  { value: "Czech Republic (+420)", label: "Czech Republic (+420)" },
  { value: "Denmark (+45)", label: "Denmark (+45)" },
  { value: "Djibouti (+253)", label: "Djibouti (+253)" },
  { value: "Dominica (+1 767)", label: "Dominica (+1 767)" },
  {
    value: "Dominican Republic (+1 809)",
    label: "Dominican Republic (+1 809)",
  },
  {
    value: "East Timor (Timor-Leste) (+670)",
    label: "East Timor (Timor-Leste) (+670)",
  },
  { value: "Ecuador (+593)", label: "Ecuador (+593)" },
  { value: "Egypt (+20)", label: "Egypt (+20)" },
  { value: "El Salvador (+503)", label: "El Salvador (+503)" },
  { value: "Equatorial Guinea (+240)", label: "Equatorial Guinea (+240)" },
  { value: "Eritrea (+291)", label: "Eritrea (+291)" },
  { value: "Estonia (+372)", label: "Estonia (+372)" },
  { value: "Eswatini (+268)", label: "Eswatini (+268)" },
  { value: "Ethiopia (+251)", label: "Ethiopia (+251)" },
  { value: "Falkland Islands (+500)", label: "Falkland Islands (+500)" },
  { value: "Faroe Islands (+298)", label: "Faroe Islands (+298)" },
  { value: "Fiji (+679)", label: "Fiji (+679)" },
  { value: "Finland (+358)", label: "Finland (+358)" },
  { value: "France (+33)", label: "France (+33)" },
  { value: "French Guiana (+594)", label: "French Guiana (+594)" },
  { value: "French Polynesia (+689)", label: "French Polynesia (+689)" },
  { value: "Gabon (+241)", label: "Gabon (+241)" },
  { value: "Gambia (+220)", label: "Gambia (+220)" },
  { value: "Georgia (+995)", label: "Georgia (+995)" },
  { value: "Germany (+49)", label: "Germany (+49)" },
  { value: "Ghana (+233)", label: "Ghana (+233)" },
  { value: "Gibraltar (+350)", label: "Gibraltar (+350)" },
  { value: "Greece (+30)", label: "Greece (+30)" },
  { value: "Greenland (+299)", label: "Greenland (+299)" },
  { value: "Grenada (+1 473)", label: "Grenada (+1 473)" },
  { value: "Guadeloupe (+590)", label: "Guadeloupe (+590)" },
  { value: "Guam (+1 671)", label: "Guam (+1 671)" },
  { value: "Guatemala (+502)", label: "Guatemala (+502)" },
  { value: "Guernsey (+44 1481)", label: "Guernsey (+44 1481)" },
  { value: "Guinea (+224)", label: "Guinea (+224)" },
  { value: "Guinea-Bissau (+245)", label: "Guinea-Bissau (+245)" },
  { value: "Guyana (+592)", label: "Guyana (+592)" },
  { value: "Haiti (+509)", label: "Haiti (+509)" },
  { value: "Honduras (+504)", label: "Honduras (+504)" },
  { value: "Hong Kong (+852)", label: "Hong Kong (+852)" },
  { value: "Hungary (+36)", label: "Hungary (+36)" },
  { value: "Iceland (+354)", label: "Iceland (+354)" },
  { value: "India (+91)", label: "India (+91)" },
  { value: "Indonesia (+62)", label: "Indonesia (+62)" },
  { value: "Iran (+98)", label: "Iran (+98)" },
  { value: "Iraq (+964)", label: "Iraq (+964)" },
  { value: "Ireland (+353)", label: "Ireland (+353)" },
  { value: "Isle of Man (+44 1624)", label: "Isle of Man (+44 1624)" },
  { value: "Israel (+972)", label: "Israel (+972)" },
  { value: "Italy (+39)", label: "Italy (+39)" },
  { value: "Jamaica (+1 876)", label: "Jamaica (+1 876)" },
  { value: "Japan (+81)", label: "Japan (+81)" },
  { value: "Jersey (+44 1534)", label: "Jersey (+44 1534)" },
  { value: "Jordan (+962)", label: "Jordan (+962)" },
  { value: "Kazakhstan (+7)", label: "Kazakhstan (+7)" },
  { value: "Kenya (+254)", label: "Kenya (+254)" },
  { value: "Kiribati (+686)", label: "Kiribati (+686)" },
  { value: "Korea, North (+850)", label: "Korea, North (+850)" },
  { value: "Korea, South (+82)", label: "Korea, South (+82)" },
  { value: "Kosovo (+383)", label: "Kosovo (+383)" },
  { value: "Kuwait (+965)", label: "Kuwait (+965)" },
  { value: "Kyrgyzstan (+996)", label: "Kyrgyzstan (+996)" },
  { value: "Laos (+856)", label: "Laos (+856)" },
  { value: "Latvia (+371)", label: "Latvia (+371)" },
  { value: "Lebanon (+961)", label: "Lebanon (+961)" },
  { value: "Lesotho (+266)", label: "Lesotho (+266)" },
  { value: "Liberia (+231)", label: "Liberia (+231)" },
  { value: "Libya (+218)", label: "Libya (+218)" },
  { value: "Liechtenstein (+423)", label: "Liechtenstein (+423)" },
  { value: "Lithuania (+370)", label: "Lithuania (+370)" },
  { value: "Luxembourg (+352)", label: "Luxembourg (+352)" },
  { value: "Macau (+853)", label: "Macau (+853)" },
  { value: "Madagascar (+261)", label: "Madagascar (+261)" },
  { value: "Malawi (+265)", label: "Malawi (+265)" },
  { value: "Malaysia (+60)", label: "Malaysia (+60)" },
  { value: "Maldives (+960)", label: "Maldives (+960)" },
  { value: "Mali (+223)", label: "Mali (+223)" },
  { value: "Malta (+356)", label: "Malta (+356)" },
  { value: "Marshall Islands (+692)", label: "Marshall Islands (+692)" },
  { value: "Martinique (+596)", label: "Martinique (+596)" },
  { value: "Mauritania (+222)", label: "Mauritania (+222)" },
  { value: "Mauritius (+230)", label: "Mauritius (+230)" },
  { value: "Mayotte (+262)", label: "Mayotte (+262)" },
  { value: "Mexico (+52)", label: "Mexico (+52)" },
  { value: "Micronesia (+691)", label: "Micronesia (+691)" },
  { value: "Moldova (+373)", label: "Moldova (+373)" },
  { value: "Monaco (+377)", label: "Monaco (+377)" },
  { value: "Mongolia (+976)", label: "Mongolia (+976)" },
  { value: "Montenegro (+382)", label: "Montenegro (+382)" },
  { value: "Montserrat (+1 664)", label: "Montserrat (+1 664)" },
  { value: "Morocco (+212)", label: "Morocco (+212)" },
  { value: "Mozambique (+258)", label: "Mozambique (+258)" },
  { value: "Myanmar (Burma) (+95)", label: "Myanmar (Burma) (+95)" },
  { value: "Namibia (+264)", label: "Namibia (+264)" },
  { value: "Nauru (+674)", label: "Nauru (+674)" },
  { value: "Nepal (+977)", label: "Nepal (+977)" },
  { value: "Netherlands (+31)", label: "Netherlands (+31)" },
  { value: "New Caledonia (+687)", label: "New Caledonia (+687)" },
  { value: "New Zealand (+64)", label: "New Zealand (+64)" },
  { value: "Nicaragua (+505)", label: "Nicaragua (+505)" },
  { value: "Niger (+227)", label: "Niger (+227)" },
  { value: "Nigeria (+234)", label: "Nigeria (+234)" },
  { value: "Niue (+683)", label: "Niue (+683)" },
  { value: "Norfolk Island (+672)", label: "Norfolk Island (+672)" },
  { value: "North Macedonia (+389)", label: "North Macedonia (+389)" },
  {
    value: "Northern Mariana Islands (+1 670)",
    label: "Northern Mariana Islands (+1 670)",
  },
  { value: "Norway (+47)", label: "Norway (+47)" },
  { value: "Oman (+968)", label: "Oman (+968)" },
  { value: "Pakistan (+92)", label: "Pakistan (+92)" },
  { value: "Palau (+680)", label: "Palau (+680)" },
  { value: "Palestine (+970)", label: "Palestine (+970)" },
  { value: "Panama (+507)", label: "Panama (+507)" },
  { value: "Papua New Guinea (+675)", label: "Papua New Guinea (+675)" },
  { value: "Paraguay (+595)", label: "Paraguay (+595)" },
  { value: "Peru (+51)", label: "Peru (+51)" },
  { value: "Philippines (+63)", label: "Philippines (+63)" },
  { value: "Poland (+48)", label: "Poland (+48)" },
  { value: "Portugal (+351)", label: "Portugal (+351)" },
  { value: "Puerto Rico (+1 787)", label: "Puerto Rico (+1 787)" },
  { value: "Qatar (+974)", label: "Qatar (+974)" },
  { value: "Réunion (+262)", label: "Réunion (+262)" },
  { value: "Romania (+40)", label: "Romania (+40)" },
  { value: "Russia (+7)", label: "Russia (+7)" },
  { value: "Rwanda (+250)", label: "Rwanda (+250)" },
  { value: "Saint Barthélemy (+590)", label: "Saint Barthélemy (+590)" },
  { value: "Saint Helena (+290)", label: "Saint Helena (+290)" },
  {
    value: "Saint Kitts and Nevis (+1 869)",
    label: "Saint Kitts and Nevis (+1 869)",
  },
  { value: "Saint Lucia (+1 758)", label: "Saint Lucia (+1 758)" },
  { value: "Saint Martin (+590)", label: "Saint Martin (+590)" },
  {
    value: "Saint Pierre and Miquelon (+508)",
    label: "Saint Pierre and Miquelon (+508)",
  },
  {
    value: "Saint Vincent and the Grenadines (+1 784)",
    label: "Saint Vincent and the Grenadines (+1 784)",
  },
  { value: "Samoa (+685)", label: "Samoa (+685)" },
  { value: "San Marino (+378)", label: "San Marino (+378)" },
  {
    value: "São Tomé and Príncipe (+239)",
    label: "São Tomé and Príncipe (+239)",
  },
  { value: "Saudi Arabia (+966)", label: "Saudi Arabia (+966)" },
  { value: "Senegal (+221)", label: "Senegal (+221)" },
  { value: "Serbia (+381)", label: "Serbia (+381)" },
  { value: "Seychelles (+248)", label: "Seychelles (+248)" },
  { value: "Sierra Leone (+232)", label: "Sierra Leone (+232)" },
  { value: "Singapore (+65)", label: "Singapore (+65)" },
  { value: "Sint Maarten (+1 721)", label: "Sint Maarten (+1 721)" },
  { value: "Slovakia (+421)", label: "Slovakia (+421)" },
  { value: "Slovenia (+386)", label: "Slovenia (+386)" },
  { value: "Solomon Islands (+677)", label: "Solomon Islands (+677)" },
  { value: "Somalia (+252)", label: "Somalia (+252)" },
  { value: "South Africa (+27)", label: "South Africa (+27)" },
  {
    value: "South Georgia and the South Sandwich Islands (+500)",
    label: "South Georgia and the South Sandwich Islands (+500)",
  },
  { value: "South Sudan (+211)", label: "South Sudan (+211)" },
  { value: "Spain (+34)", label: "Spain (+34)" },
  { value: "Sri Lanka (+94)", label: "Sri Lanka (+94)" },
  { value: "Sudan (+249)", label: "Sudan (+249)" },
  { value: "Suriname (+597)", label: "Suriname (+597)" },
  {
    value: "Svalbard and Jan Mayen (+47)",
    label: "Svalbard and Jan Mayen (+47)",
  },
  { value: "Sweden (+46)", label: "Sweden (+46)" },
  { value: "Switzerland (+41)", label: "Switzerland (+41)" },
  { value: "Syria (+963)", label: "Syria (+963)" },
  { value: "Taiwan (+886)", label: "Taiwan (+886)" },
  { value: "Tajikistan (+992)", label: "Tajikistan (+992)" },
  { value: "Tanzania (+255)", label: "Tanzania (+255)" },
  { value: "Thailand (+66)", label: "Thailand (+66)" },
  { value: "Timor-Leste (+670)", label: "Timor-Leste (+670)" },
  { value: "Togo (+228)", label: "Togo (+228)" },
  { value: "Tokelau (+690)", label: "Tokelau (+690)" },
  { value: "Tonga (+676)", label: "Tonga (+676)" },
  {
    value: "Trinidad and Tobago (+1 868)",
    label: "Trinidad and Tobago (+1 868)",
  },
  { value: "Tunisia (+216)", label: "Tunisia (+216)" },
  { value: "Turkey (+90)", label: "Turkey (+90)" },
  { value: "Turkmenistan (+993)", label: "Turkmenistan (+993)" },
  {
    value: "Turks and Caicos Islands (+1 649)",
    label: "Turks and Caicos Islands (+1 649)",
  },
  { value: "Tuvalu (+688)", label: "Tuvalu (+688)" },
  {
    value: "U.S. Virgin Islands (+1 340)",
    label: "U.S. Virgin Islands (+1 340)",
  },
  { value: "Uganda (+256)", label: "Uganda (+256)" },
  { value: "Ukraine (+380)", label: "Ukraine (+380)" },
  {
    value: "United Arab Emirates (+971)",
    label: "United Arab Emirates (+971)",
  },
  { value: "United Kingdom (+44)", label: "United Kingdom (+44)" },
  { value: "United States (+1)", label: "United States (+1)" },
  { value: "Uruguay (+598)", label: "Uruguay (+598)" },
  { value: "Uzbekistan (+998)", label: "Uzbekistan (+998)" },
  { value: "Vanuatu (+678)", label: "Vanuatu (+678)" },
  { value: "Vatican City (+39 06)", label: "Vatican City (+39 06)" },
  { value: "Venezuela (+58)", label: "Venezuela (+58)" },
  { value: "Vietnam (+84)", label: "Vietnam (+84)" },
  { value: "Wallis and Futuna (+681)", label: "Wallis and Futuna (+681)" },
  { value: "Western Sahara (+212)", label: "Western Sahara (+212)" },
  { value: "Yemen (+967)", label: "Yemen (+967)" },
  { value: "Zambia (+260)", label: "Zambia (+260)" },
  { value: "Zimbabwe (+263)", label: "Zimbabwe (+263)" },
];

export const countriesOptions = [
  { value: "Afghanistan", label: "Afghanistan" },
  { value: "Albania", label: "Albania" },
  { value: "Algeria", label: "Algeria" },
  { value: "American Samoa", label: "American Samoa" },
  { value: "Andorra", label: "Andorra" },
  { value: "Angola", label: "Angola" },
  { value: "Anguilla", label: "Anguilla" },
  { value: "Antarctica", label: "Antarctica" },
  {
    value: "Antigua and Barbuda",
    label: "Antigua and Barbuda",
  },
  { value: "Argentina", label: "Argentina" },
  { value: "Armenia", label: "Armenia" },
  { value: "Aruba", label: "Aruba" },
  { value: "Australia", label: "Australia" },
  { value: "Austria", label: "Austria" },
  { value: "Azerbaijan", label: "Azerbaijan" },
  { value: "Bahamas", label: "Bahamas" },
  { value: "Bahrain", label: "Bahrain" },
  { value: "Bangladesh", label: "Bangladesh" },
  { value: "Barbados", label: "Barbados" },
  { value: "Belarus", label: "Belarus" },
  { value: "Belgium", label: "Belgium" },
  { value: "Belize", label: "Belize" },
  { value: "Benin", label: "Benin" },
  { value: "Bermuda", label: "Bermuda" },
  { value: "Bhutan", label: "Bhutan" },
  { value: "Bolivia", label: "Bolivia" },
  {
    value: "Bosnia and Herzegovina (+387)",
    label: "Bosnia and Herzegovina (+387)",
  },
  { value: "Botswana", label: "Botswana" },
  { value: "Brazil", label: "Brazil" },
  {
    value: "British Indian Ocean Territory",
    label: "British Indian Ocean Territory",
  },
  { value: "British Virgin Islands", label: "British Virgin Islands" },
  { value: "Brunei", label: "Brunei" },
  { value: "Bulgaria", label: "Bulgaria" },
  { value: "Burkina Faso", label: "Burkina Faso" },
  { value: "Burundi", label: "Burundi" },
  { value: "Cambodia", label: "Cambodia" },
  { value: "Cameroon", label: "Cameroon" },
  { value: "Canada", label: "Canada" },
  { value: "Cape Verde", label: "Cape Verde" },
  { value: "Caribbean Netherlands", label: "Caribbean Netherlands" },
  { value: "Cayman Islands", label: "Cayman Islands" },
  {
    value: "Central African Republic (+236)",
    label: "Central African Republic (+236)",
  },
  { value: "Chad (+235)", label: "Chad (+235)" },
  { value: "Chile (+56)", label: "Chile (+56)" },
  { value: "China (+86)", label: "China (+86)" },
  { value: "Christmas Island (+61)", label: "Christmas Island (+61)" },
  {
    value: "Cocos (Keeling) Islands (+61)",
    label: "Cocos (Keeling) Islands (+61)",
  },
  { value: "Colombia (+57)", label: "Colombia (+57)" },
  { value: "Comoros (+269)", label: "Comoros (+269)" },
  { value: "Congo (DRC) (+243)", label: "Congo (DRC) (+243)" },
  { value: "Congo (Republic) (+242)", label: "Congo (Republic) (+242)" },
  { value: "Cook Islands (+682)", label: "Cook Islands (+682)" },
  { value: "Costa Rica (+506)", label: "Costa Rica (+506)" },
  { value: "Côte d'Ivoire (+225)", label: "Côte d'Ivoire (+225)" },
  { value: "Croatia (+385)", label: "Croatia (+385)" },
  { value: "Cuba (+53)", label: "Cuba (+53)" },
  { value: "Curaçao (+599)", label: "Curaçao (+599)" },
  { value: "Cyprus (+357)", label: "Cyprus (+357)" },
  { value: "Czech Republic (+420)", label: "Czech Republic (+420)" },
  { value: "Denmark (+45)", label: "Denmark (+45)" },
  { value: "Djibouti (+253)", label: "Djibouti (+253)" },
  { value: "Dominica (+1 767)", label: "Dominica (+1 767)" },
  {
    value: "Dominican Republic (+1 809)",
    label: "Dominican Republic (+1 809)",
  },
  {
    value: "East Timor (Timor-Leste) (+670)",
    label: "East Timor (Timor-Leste) (+670)",
  },
  { value: "Ecuador (+593)", label: "Ecuador (+593)" },
  { value: "Egypt (+20)", label: "Egypt (+20)" },
  { value: "El Salvador (+503)", label: "El Salvador (+503)" },
  { value: "Equatorial Guinea (+240)", label: "Equatorial Guinea (+240)" },
  { value: "Eritrea (+291)", label: "Eritrea (+291)" },
  { value: "Estonia (+372)", label: "Estonia (+372)" },
  { value: "Eswatini (+268)", label: "Eswatini (+268)" },
  { value: "Ethiopia (+251)", label: "Ethiopia (+251)" },
  { value: "Falkland Islands (+500)", label: "Falkland Islands (+500)" },
  { value: "Faroe Islands (+298)", label: "Faroe Islands (+298)" },
  { value: "Fiji (+679)", label: "Fiji (+679)" },
  { value: "Finland (+358)", label: "Finland (+358)" },
  { value: "France (+33)", label: "France (+33)" },
  { value: "French Guiana (+594)", label: "French Guiana (+594)" },
  { value: "French Polynesia (+689)", label: "French Polynesia (+689)" },
  { value: "Gabon (+241)", label: "Gabon (+241)" },
  { value: "Gambia (+220)", label: "Gambia (+220)" },
  { value: "Georgia (+995)", label: "Georgia (+995)" },
  { value: "Germany (+49)", label: "Germany (+49)" },
  { value: "Ghana (+233)", label: "Ghana (+233)" },
  { value: "Gibraltar (+350)", label: "Gibraltar (+350)" },
  { value: "Greece (+30)", label: "Greece (+30)" },
  { value: "Greenland (+299)", label: "Greenland (+299)" },
  { value: "Grenada (+1 473)", label: "Grenada (+1 473)" },
  { value: "Guadeloupe (+590)", label: "Guadeloupe (+590)" },
  { value: "Guam (+1 671)", label: "Guam (+1 671)" },
  { value: "Guatemala (+502)", label: "Guatemala (+502)" },
  { value: "Guernsey (+44 1481)", label: "Guernsey (+44 1481)" },
  { value: "Guinea (+224)", label: "Guinea (+224)" },
  { value: "Guinea-Bissau (+245)", label: "Guinea-Bissau (+245)" },
  { value: "Guyana (+592)", label: "Guyana (+592)" },
  { value: "Haiti (+509)", label: "Haiti (+509)" },
  { value: "Honduras (+504)", label: "Honduras (+504)" },
  { value: "Hong Kong (+852)", label: "Hong Kong (+852)" },
  { value: "Hungary (+36)", label: "Hungary (+36)" },
  { value: "Iceland (+354)", label: "Iceland (+354)" },
  { value: "India (+91)", label: "India (+91)" },
  { value: "Indonesia (+62)", label: "Indonesia (+62)" },
  { value: "Iran (+98)", label: "Iran (+98)" },
  { value: "Iraq (+964)", label: "Iraq (+964)" },
  { value: "Ireland (+353)", label: "Ireland (+353)" },
  { value: "Isle of Man (+44 1624)", label: "Isle of Man (+44 1624)" },
  { value: "Israel (+972)", label: "Israel (+972)" },
  { value: "Italy (+39)", label: "Italy (+39)" },
  { value: "Jamaica (+1 876)", label: "Jamaica (+1 876)" },
  { value: "Japan (+81)", label: "Japan (+81)" },
  { value: "Jersey (+44 1534)", label: "Jersey (+44 1534)" },
  { value: "Jordan (+962)", label: "Jordan (+962)" },
  { value: "Kazakhstan (+7)", label: "Kazakhstan (+7)" },
  { value: "Kenya (+254)", label: "Kenya (+254)" },
  { value: "Kiribati (+686)", label: "Kiribati (+686)" },
  { value: "Korea, North (+850)", label: "Korea, North (+850)" },
  { value: "Korea, South (+82)", label: "Korea, South (+82)" },
  { value: "Kosovo (+383)", label: "Kosovo (+383)" },
  { value: "Kuwait (+965)", label: "Kuwait (+965)" },
  { value: "Kyrgyzstan (+996)", label: "Kyrgyzstan (+996)" },
  { value: "Laos (+856)", label: "Laos (+856)" },
  { value: "Latvia (+371)", label: "Latvia (+371)" },
  { value: "Lebanon (+961)", label: "Lebanon (+961)" },
  { value: "Lesotho (+266)", label: "Lesotho (+266)" },
  { value: "Liberia (+231)", label: "Liberia (+231)" },
  { value: "Libya (+218)", label: "Libya (+218)" },
  { value: "Liechtenstein (+423)", label: "Liechtenstein (+423)" },
  { value: "Lithuania (+370)", label: "Lithuania (+370)" },
  { value: "Luxembourg (+352)", label: "Luxembourg (+352)" },
  { value: "Macau (+853)", label: "Macau (+853)" },
  { value: "Madagascar (+261)", label: "Madagascar (+261)" },
  { value: "Malawi (+265)", label: "Malawi (+265)" },
  { value: "Malaysia (+60)", label: "Malaysia (+60)" },
  { value: "Maldives (+960)", label: "Maldives (+960)" },
  { value: "Mali (+223)", label: "Mali (+223)" },
  { value: "Malta (+356)", label: "Malta (+356)" },
  { value: "Marshall Islands (+692)", label: "Marshall Islands (+692)" },
  { value: "Martinique (+596)", label: "Martinique (+596)" },
  { value: "Mauritania (+222)", label: "Mauritania (+222)" },
  { value: "Mauritius (+230)", label: "Mauritius (+230)" },
  { value: "Mayotte (+262)", label: "Mayotte (+262)" },
  { value: "Mexico (+52)", label: "Mexico (+52)" },
  { value: "Micronesia (+691)", label: "Micronesia (+691)" },
  { value: "Moldova (+373)", label: "Moldova (+373)" },
  { value: "Monaco (+377)", label: "Monaco (+377)" },
  { value: "Mongolia (+976)", label: "Mongolia (+976)" },
  { value: "Montenegro (+382)", label: "Montenegro (+382)" },
  { value: "Montserrat (+1 664)", label: "Montserrat (+1 664)" },
  { value: "Morocco (+212)", label: "Morocco (+212)" },
  { value: "Mozambique (+258)", label: "Mozambique (+258)" },
  { value: "Myanmar (Burma) (+95)", label: "Myanmar (Burma) (+95)" },
  { value: "Namibia (+264)", label: "Namibia (+264)" },
  { value: "Nauru (+674)", label: "Nauru (+674)" },
  { value: "Nepal (+977)", label: "Nepal (+977)" },
  { value: "Netherlands (+31)", label: "Netherlands (+31)" },
  { value: "New Caledonia (+687)", label: "New Caledonia (+687)" },
  { value: "New Zealand (+64)", label: "New Zealand (+64)" },
  { value: "Nicaragua (+505)", label: "Nicaragua (+505)" },
  { value: "Niger (+227)", label: "Niger (+227)" },
  { value: "Nigeria (+234)", label: "Nigeria (+234)" },
  { value: "Niue (+683)", label: "Niue (+683)" },
  { value: "Norfolk Island (+672)", label: "Norfolk Island (+672)" },
  { value: "North Macedonia (+389)", label: "North Macedonia (+389)" },
  {
    value: "Northern Mariana Islands (+1 670)",
    label: "Northern Mariana Islands (+1 670)",
  },
  { value: "Norway (+47)", label: "Norway (+47)" },
  { value: "Oman (+968)", label: "Oman (+968)" },
  { value: "Pakistan (+92)", label: "Pakistan (+92)" },
  { value: "Palau (+680)", label: "Palau (+680)" },
  { value: "Palestine (+970)", label: "Palestine (+970)" },
  { value: "Panama (+507)", label: "Panama (+507)" },
  { value: "Papua New Guinea (+675)", label: "Papua New Guinea (+675)" },
  { value: "Paraguay (+595)", label: "Paraguay (+595)" },
  { value: "Peru (+51)", label: "Peru (+51)" },
  { value: "Philippines (+63)", label: "Philippines (+63)" },
  { value: "Poland (+48)", label: "Poland (+48)" },
  { value: "Portugal (+351)", label: "Portugal (+351)" },
  { value: "Puerto Rico (+1 787)", label: "Puerto Rico (+1 787)" },
  { value: "Qatar (+974)", label: "Qatar (+974)" },
  { value: "Réunion (+262)", label: "Réunion (+262)" },
  { value: "Romania (+40)", label: "Romania (+40)" },
  { value: "Russia (+7)", label: "Russia (+7)" },
  { value: "Rwanda (+250)", label: "Rwanda (+250)" },
  { value: "Saint Barthélemy (+590)", label: "Saint Barthélemy (+590)" },
  { value: "Saint Helena (+290)", label: "Saint Helena (+290)" },
  {
    value: "Saint Kitts and Nevis (+1 869)",
    label: "Saint Kitts and Nevis (+1 869)",
  },
  { value: "Saint Lucia (+1 758)", label: "Saint Lucia (+1 758)" },
  { value: "Saint Martin (+590)", label: "Saint Martin (+590)" },
  {
    value: "Saint Pierre and Miquelon (+508)",
    label: "Saint Pierre and Miquelon (+508)",
  },
  {
    value: "Saint Vincent and the Grenadines (+1 784)",
    label: "Saint Vincent and the Grenadines (+1 784)",
  },
  { value: "Samoa (+685)", label: "Samoa (+685)" },
  { value: "San Marino (+378)", label: "San Marino (+378)" },
  {
    value: "São Tomé and Príncipe (+239)",
    label: "São Tomé and Príncipe (+239)",
  },
  { value: "Saudi Arabia (+966)", label: "Saudi Arabia (+966)" },
  { value: "Senegal (+221)", label: "Senegal (+221)" },
  { value: "Serbia (+381)", label: "Serbia (+381)" },
  { value: "Seychelles (+248)", label: "Seychelles (+248)" },
  { value: "Sierra Leone (+232)", label: "Sierra Leone (+232)" },
  { value: "Singapore (+65)", label: "Singapore (+65)" },
  { value: "Sint Maarten (+1 721)", label: "Sint Maarten (+1 721)" },
  { value: "Slovakia (+421)", label: "Slovakia (+421)" },
  { value: "Slovenia (+386)", label: "Slovenia (+386)" },
  { value: "Solomon Islands (+677)", label: "Solomon Islands (+677)" },
  { value: "Somalia (+252)", label: "Somalia (+252)" },
  { value: "South Africa (+27)", label: "South Africa (+27)" },
  {
    value: "South Georgia and the South Sandwich Islands (+500)",
    label: "South Georgia and the South Sandwich Islands (+500)",
  },
  { value: "South Sudan (+211)", label: "South Sudan (+211)" },
  { value: "Spain (+34)", label: "Spain (+34)" },
  { value: "Sri Lanka (+94)", label: "Sri Lanka (+94)" },
  { value: "Sudan (+249)", label: "Sudan (+249)" },
  { value: "Suriname (+597)", label: "Suriname (+597)" },
  {
    value: "Svalbard and Jan Mayen (+47)",
    label: "Svalbard and Jan Mayen (+47)",
  },
  { value: "Sweden (+46)", label: "Sweden (+46)" },
  { value: "Switzerland (+41)", label: "Switzerland (+41)" },
  { value: "Syria (+963)", label: "Syria (+963)" },
  { value: "Taiwan (+886)", label: "Taiwan (+886)" },
  { value: "Tajikistan (+992)", label: "Tajikistan (+992)" },
  { value: "Tanzania (+255)", label: "Tanzania (+255)" },
  { value: "Thailand (+66)", label: "Thailand (+66)" },
  { value: "Timor-Leste (+670)", label: "Timor-Leste (+670)" },
  { value: "Togo (+228)", label: "Togo (+228)" },
  { value: "Tokelau (+690)", label: "Tokelau (+690)" },
  { value: "Tonga (+676)", label: "Tonga (+676)" },
  {
    value: "Trinidad and Tobago (+1 868)",
    label: "Trinidad and Tobago (+1 868)",
  },
  { value: "Tunisia (+216)", label: "Tunisia (+216)" },
  { value: "Turkey (+90)", label: "Turkey (+90)" },
  { value: "Turkmenistan (+993)", label: "Turkmenistan (+993)" },
  {
    value: "Turks and Caicos Islands (+1 649)",
    label: "Turks and Caicos Islands (+1 649)",
  },
  { value: "Tuvalu (+688)", label: "Tuvalu (+688)" },
  {
    value: "U.S. Virgin Islands (+1 340)",
    label: "U.S. Virgin Islands (+1 340)",
  },
  { value: "Uganda (+256)", label: "Uganda (+256)" },
  { value: "Ukraine (+380)", label: "Ukraine (+380)" },
  {
    value: "United Arab Emirates (+971)",
    label: "United Arab Emirates (+971)",
  },
  { value: "United Kingdom (+44)", label: "United Kingdom (+44)" },
  { value: "United States (+1)", label: "United States (+1)" },
  { value: "Uruguay (+598)", label: "Uruguay (+598)" },
  { value: "Uzbekistan (+998)", label: "Uzbekistan (+998)" },
  { value: "Vanuatu (+678)", label: "Vanuatu (+678)" },
  { value: "Vatican City (+39 06)", label: "Vatican City (+39 06)" },
  { value: "Venezuela (+58)", label: "Venezuela (+58)" },
  { value: "Vietnam (+84)", label: "Vietnam (+84)" },
  { value: "Wallis and Futuna (+681)", label: "Wallis and Futuna (+681)" },
  { value: "Western Sahara (+212)", label: "Western Sahara (+212)" },
  { value: "Yemen (+967)", label: "Yemen (+967)" },
  { value: "Zambia (+260)", label: "Zambia (+260)" },
  { value: "Zimbabwe (+263)", label: "Zimbabwe (+263)" },
];

export const countries = [
  {
    name: "Afghanistan",
    code: "+93",
  },
  {
    name: "Albania",
    code: "+355",
  },
  {
    name: "Algeria",
    code: "+213",
  },
  {
    name: "American Samoa",
    code: "+1 684",
  },
  {
    name: "Andorra",
    code: "+376",
  },
  {
    name: "Angola",
    code: "+244",
  },
  {
    name: "Anguilla",
    code: "+1 264",
  },
  {
    name: "Antarctica",
    code: "+672",
  },
  {
    name: "Antigua and Barbuda",
    code: "+1 268",
  },
  {
    name: "Argentina",
    code: "+54",
  },
  {
    name: "Armenia",
    code: "+374",
  },
  {
    name: "Aruba",
    code: "+297",
  },
  {
    name: "Australia",
    code: "+61",
  },
  {
    name: "Austria",
    code: "+43",
  },
  {
    name: "Azerbaijan",
    code: "+994",
  },
  {
    name: "Bahamas",
    code: "+1 242",
  },
  {
    name: "Bahrain",
    code: "+973",
  },
  {
    name: "Bangladesh",
    code: "+880",
  },
  {
    name: "Barbados",
    code: "+1 246",
  },
  {
    name: "Belarus",
    code: "+375",
  },
  {
    name: "Belgium",
    code: "+32",
  },
  {
    name: "Belize",
    code: "+501",
  },
  {
    name: "Benin",
    code: "+229",
  },
  {
    name: "Bermuda",
    code: "+1 441",
  },
  {
    name: "Bhutan",
    code: "+975",
  },
  {
    name: "Bolivia",
    code: "+591",
  },
  {
    name: "Bosnia and Herzegovina",
    code: "+387",
  },
  {
    name: "Botswana",
    code: "+267",
  },
  {
    name: "Brazil",
    code: "+55",
  },
  {
    name: "British Indian Ocean Territory",
    code: "+246",
  },
  {
    name: "British Virgin Islands",
    code: "+1 284",
  },
  {
    name: "Brunei",
    code: "+673",
  },
  {
    name: "Bulgaria",
    code: "+359",
  },
  {
    name: "Burkina Faso",
    code: "+226",
  },
  {
    name: "Burundi",
    code: "+257",
  },
  {
    name: "Cambodia",
    code: "+855",
  },
  {
    name: "Cameroon",
    code: "+237",
  },
  {
    name: "Canada",
    code: "+1",
  },
  {
    name: "Cape Verde",
    code: "+238",
  },
  {
    name: "Caribbean Netherlands",
    code: "+599",
  },
  {
    name: "Cayman Islands",
    code: "+1 345",
  },
  {
    name: "Central African Republic",
    code: "+236",
  },
  {
    name: "Chad",
    code: "+235",
  },
  {
    name: "Chile",
    code: "+56",
  },
  {
    name: "China",
    code: "+86",
  },
  {
    name: "Christmas Island",
    code: "+61",
  },
  {
    name: "CocosIslands (+61)",
    code: "Keeling",
  },
  {
    name: "Colombia",
    code: "+57",
  },
  {
    name: "Comoros",
    code: "+269",
  },
  {
    name: "Congo(+243)",
    code: "DRC",
  },
  {
    name: "Congo(+242)",
    code: "Republic",
  },
  {
    name: "Cook Islands",
    code: "+682",
  },
  {
    name: "Costa Rica",
    code: "+506",
  },
  {
    name: "Côte d'Ivoire",
    code: "+225",
  },
  {
    name: "Croatia",
    code: "+385",
  },
  {
    name: "Cuba",
    code: "+53",
  },
  {
    name: "Curaçao",
    code: "+599",
  },
  {
    name: "Cyprus",
    code: "+357",
  },
  {
    name: "Czech Republic",
    code: "+420",
  },
  {
    name: "Denmark",
    code: "+45",
  },
  {
    name: "Djibouti",
    code: "+253",
  },
  {
    name: "Dominica",
    code: "+1 767",
  },
  {
    name: "Dominican Republic",
    code: "+1 809",
  },
  {
    name: "East Timor(+670)",
    code: "Timor-Leste",
  },
  {
    name: "Ecuador",
    code: "+593",
  },
  {
    name: "Egypt",
    code: "+20",
  },
  {
    name: "El Salvador",
    code: "+503",
  },
  {
    name: "Equatorial Guinea",
    code: "+240",
  },
  {
    name: "Eritrea",
    code: "+291",
  },
  {
    name: "Estonia",
    code: "+372",
  },
  {
    name: "Eswatini",
    code: "+268",
  },
  {
    name: "Ethiopia",
    code: "+251",
  },
  {
    name: "Falkland Islands",
    code: "+500",
  },
  {
    name: "Faroe Islands",
    code: "+298",
  },
  {
    name: "Fiji",
    code: "+679",
  },
  {
    name: "Finland",
    code: "+358",
  },
  {
    name: "France",
    code: "+33",
  },
  {
    name: "French Guiana",
    code: "+594",
  },
  {
    name: "French Polynesia",
    code: "+689",
  },
  {
    name: "Gabon",
    code: "+241",
  },
  {
    name: "Gambia",
    code: "+220",
  },
  {
    name: "Georgia",
    code: "+995",
  },
  {
    name: "Germany",
    code: "+49",
  },
  {
    name: "Ghana",
    code: "+233",
  },
  {
    name: "Gibraltar",
    code: "+350",
  },
  {
    name: "Greece",
    code: "+30",
  },
  {
    name: "Greenland",
    code: "+299",
  },
  {
    name: "Grenada",
    code: "+1 473",
  },
  {
    name: "Guadeloupe",
    code: "+590",
  },
  {
    name: "Guam",
    code: "+1 671",
  },
  {
    name: "Guatemala",
    code: "+502",
  },
  {
    name: "Guernsey",
    code: "+44 1481",
  },
  {
    name: "Guinea",
    code: "+224",
  },
  {
    name: "Guinea-Bissau",
    code: "+245",
  },
  {
    name: "Guyana",
    code: "+592",
  },
  {
    name: "Haiti",
    code: "+509",
  },
  {
    name: "Honduras",
    code: "+504",
  },
  {
    name: "Hong Kong",
    code: "+852",
  },
  {
    name: "Hungary",
    code: "+36",
  },
  {
    name: "Iceland",
    code: "+354",
  },
  {
    name: "India",
    code: "+91",
  },
  {
    name: "Indonesia",
    code: "+62",
  },
  {
    name: "Iran",
    code: "+98",
  },
  {
    name: "Iraq",
    code: "+964",
  },
  {
    name: "Ireland",
    code: "+353",
  },
  {
    name: "Isle of Man",
    code: "+44 1624",
  },
  {
    name: "Israel",
    code: "+972",
  },
  {
    name: "Italy",
    code: "+39",
  },
  {
    name: "Jamaica",
    code: "+1 876",
  },
  {
    name: "Japan",
    code: "+81",
  },
  {
    name: "Jersey",
    code: "+44 1534",
  },
  {
    name: "Jordan",
    code: "+962",
  },
  {
    name: "Kazakhstan",
    code: "+7",
  },
  {
    name: "Kenya",
    code: "+254",
  },
  {
    name: "Kiribati",
    code: "+686",
  },
  {
    name: "Korea, North",
    code: "+850",
  },
  {
    name: "Korea, South",
    code: "+82",
  },
  {
    name: "Kosovo",
    code: "+383",
  },
  {
    name: "Kuwait",
    code: "+965",
  },
  {
    name: "Kyrgyzstan",
    code: "+996",
  },
  {
    name: "Laos",
    code: "+856",
  },
  {
    name: "Latvia",
    code: "+371",
  },
  {
    name: "Lebanon",
    code: "+961",
  },
  {
    name: "Lesotho",
    code: "+266",
  },
  {
    name: "Liberia",
    code: "+231",
  },
  {
    name: "Libya",
    code: "+218",
  },
  {
    name: "Liechtenstein",
    code: "+423",
  },
  {
    name: "Lithuania",
    code: "+370",
  },
  {
    name: "Luxembourg",
    code: "+352",
  },
  {
    name: "Macau",
    code: "+853",
  },
  {
    name: "Madagascar",
    code: "+261",
  },
  {
    name: "Malawi",
    code: "+265",
  },
  {
    name: "Malaysia",
    code: "+60",
  },
  {
    name: "Maldives",
    code: "+960",
  },
  {
    name: "Mali",
    code: "+223",
  },
  {
    name: "Malta",
    code: "+356",
  },
  {
    name: "Marshall Islands",
    code: "+692",
  },
  {
    name: "Martinique",
    code: "+596",
  },
  {
    name: "Mauritania",
    code: "+222",
  },
  {
    name: "Mauritius",
    code: "+230",
  },
  {
    name: "Mayotte",
    code: "+262",
  },
  {
    name: "Mexico",
    code: "+52",
  },
  {
    name: "Micronesia",
    code: "+691",
  },
  {
    name: "Moldova",
    code: "+373",
  },
  {
    name: "Monaco",
    code: "+377",
  },
  {
    name: "Mongolia",
    code: "+976",
  },
  {
    name: "Montenegro",
    code: "+382",
  },
  {
    name: "Montserrat",
    code: "+1 664",
  },
  {
    name: "Morocco",
    code: "+212",
  },
  {
    name: "Mozambique",
    code: "+258",
  },
  {
    name: "Myanmar(+95)",
    code: "Burma",
  },
  {
    name: "Namibia",
    code: "+264",
  },
  {
    name: "Nauru",
    code: "+674",
  },
  {
    name: "Nepal",
    code: "+977",
  },
  {
    name: "Netherlands",
    code: "+31",
  },
  {
    name: "New Caledonia",
    code: "+687",
  },
  {
    name: "New Zealand",
    code: "+64",
  },
  {
    name: "Nicaragua",
    code: "+505",
  },
  {
    name: "Niger",
    code: "+227",
  },
  {
    name: "Nigeria",
    code: "+234",
  },
  {
    name: "Niue",
    code: "+683",
  },
  {
    name: "Norfolk Island",
    code: "+672",
  },
  {
    name: "North Macedonia",
    code: "+389",
  },
  {
    name: "Northern Mariana Islands",
    code: "+1 670",
  },
  {
    name: "Norway",
    code: "+47",
  },
  {
    name: "Oman",
    code: "+968",
  },
  {
    name: "Pakistan",
    code: "+92",
  },
  {
    name: "Palau",
    code: "+680",
  },
  {
    name: "Palestine",
    code: "+970",
  },
  {
    name: "Panama",
    code: "+507",
  },
  {
    name: "Papua New Guinea",
    code: "+675",
  },
  {
    name: "Paraguay",
    code: "+595",
  },
  {
    name: "Peru",
    code: "+51",
  },
  {
    name: "Philippines",
    code: "+63",
  },
  {
    name: "Poland",
    code: "+48",
  },
  {
    name: "Portugal",
    code: "+351",
  },
  {
    name: "Puerto Rico",
    code: "+1 787",
  },
  {
    name: "Qatar",
    code: "+974",
  },
  {
    name: "Réunion",
    code: "+262",
  },
  {
    name: "Romania",
    code: "+40",
  },
  {
    name: "Russia",
    code: "+7",
  },
  {
    name: "Rwanda",
    code: "+250",
  },
  {
    name: "Saint Barthélemy",
    code: "+590",
  },
  {
    name: "Saint Helena",
    code: "+290",
  },
  {
    name: "Saint Kitts and Nevis",
    code: "+1 869",
  },
  {
    name: "Saint Lucia",
    code: "+1 758",
  },
  {
    name: "Saint Martin",
    code: "+590",
  },
  {
    name: "Saint Pierre and Miquelon",
    code: "+508",
  },
  {
    name: "Saint Vincent and the Grenadines",
    code: "+1 784",
  },
  {
    name: "Samoa",
    code: "+685",
  },
  {
    name: "San Marino",
    code: "+378",
  },
  {
    name: "São Tomé and Príncipe",
    code: "+239",
  },
  {
    name: "Saudi Arabia",
    code: "+966",
  },
  {
    name: "Senegal",
    code: "+221",
  },
  {
    name: "Serbia",
    code: "+381",
  },
  {
    name: "Seychelles",
    code: "+248",
  },
  {
    name: "Sierra Leone",
    code: "+232",
  },
  {
    name: "Singapore",
    code: "+65",
  },
  {
    name: "Sint Maarten",
    code: "+1 721",
  },
  {
    name: "Slovakia",
    code: "+421",
  },
  {
    name: "Slovenia",
    code: "+386",
  },
  {
    name: "Solomon Islands",
    code: "+677",
  },
  {
    name: "Somalia",
    code: "+252",
  },
  {
    name: "South Africa",
    code: "+27",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    code: "+500",
  },
  {
    name: "South Sudan",
    code: "+211",
  },
  {
    name: "Spain",
    code: "+34",
  },
  {
    name: "Sri Lanka",
    code: "+94",
  },
  {
    name: "Sudan",
    code: "+249",
  },
  {
    name: "Suriname",
    code: "+597",
  },
  {
    name: "Svalbard and Jan Mayen",
    code: "+47",
  },
  {
    name: "Sweden",
    code: "+46",
  },
  {
    name: "Switzerland",
    code: "+41",
  },
  {
    name: "Syria",
    code: "+963",
  },
  {
    name: "Taiwan",
    code: "+886",
  },
  {
    name: "Tajikistan",
    code: "+992",
  },
  {
    name: "Tanzania",
    code: "+255",
  },
  {
    name: "Thailand",
    code: "+66",
  },
  {
    name: "Timor-Leste",
    code: "+670",
  },
  {
    name: "Togo",
    code: "+228",
  },
  {
    name: "Tokelau",
    code: "+690",
  },
  {
    name: "Tonga",
    code: "+676",
  },
  {
    name: "Trinidad and Tobago",
    code: "+1 868",
  },
  {
    name: "Tunisia",
    code: "+216",
  },
  {
    name: "Turkey",
    code: "+90",
  },
  {
    name: "Turkmenistan",
    code: "+993",
  },
  {
    name: "Turks and Caicos Islands",
    code: "+1 649",
  },
  {
    name: "Tuvalu",
    code: "+688",
  },
  {
    name: "U.S. Virgin Islands",
    code: "+1 340",
  },
  {
    name: "Uganda",
    code: "+256",
  },
  {
    name: "Ukraine",
    code: "+380",
  },
  {
    name: "United Arab Emirates",
    code: "+971",
  },
  {
    name: "United Kingdom",
    code: "+44",
  },
  {
    name: "United States",
    code: "+1",
  },
  {
    name: "Uruguay",
    code: "+598",
  },
  {
    name: "Uzbekistan",
    code: "+998",
  },
  {
    name: "Vanuatu",
    code: "+678",
  },
  {
    name: "Vatican City",
    code: "+39 06",
  },
  {
    name: "Venezuela",
    code: "+58",
  },
  {
    name: "Vietnam",
    code: "+84",
  },
  {
    name: "Wallis and Futuna",
    code: "+681",
  },
  {
    name: "Western Sahara",
    code: "+212",
  },
  {
    name: "Yemen",
    code: "+967",
  },
  {
    name: "Zambia",
    code: "+260",
  },
  {
    name: "Zimbabwe",
    code: "+263",
  },
];

export const countries1 = countries.map((ct, i) => {
  return {
    value: ct.name,
    label: ct.name,
    code: ct.code,
  };
});

export const countries2 = countries.map((ct, i) => {
  return {
    value: `${ct.name} (${ct.code})`,
    label: `${ct.name} (${ct.code})`,
    code: ct.code,
  };
});

// export const countries3 = countries.map((ct, i) => {
//   return {
//     value: `${ct.name} (${ct.code})`,
//     label: `${ct.name} (${ct.code})`,
//     // code: ct.code,
//   };
// });

export const phoneCodesOptionsRefactored = phoneCodesOptions.map(
  ({ value, label }) => {
    let code = value.match(/\(([^)]+)\)/)[1]; // Extracts content within the brackets
    label = value.replace(/\s*\([^)]*\)\s*/, ""); // Removes content within the brackets
    value = value.replace(/\s*\([^)]*\)\s*/, ""); // Removes content within the brackets
    return { value, label, code };
  }
);

export const phoneCodesOptionsRefactored2 = phoneCodesOptions.map(
  ({ value, label }) => {
    let code = value.match(/\(([^)]+)\)/)[1]; // Extracts content within the brackets
    // label = value.replace(/\s*\([^)]*\)\s*/, ""); // Removes content within the brackets
    value = value.replace(/\s*\([^)]*\)\s*/, ""); // Removes content within the brackets
    return { value, label, code };
  }
);
