export const city = [
  {
    name: "East London",
    id: "eastLondon",
    status: false,
    subs: [
      "Acle",
      "Aldeburgh",
      "Ampthill",
      "Arlesey",
      "Attleborough",
      "Aylsham",
      "Baldock",
      "Barton-le-Clay",
      "Basildon",
      "Bedford",
      "Beccles",
      "Berkhamsted",
      "Biggleswade",
      "Billericay",
      "Bishop’s Stortford",
      "Borehamwood",
      "Brandon",
      "Braintree",
      "Brentwood",
      "Brightlingsea",
      "Bungay",
      "Buntingford",
      "Burnham-on-Crouch",
      "Bury St. Edmunds",
      "Bushey",
      "Cambridge",
      "Cambridgeshire",
      "Canvey Island",
      "Carlton Colville",
      "Chatteris",
      "Chelmsford",
      "Cheshunt",
      "Chigwell",
      "Chipping Ongar",
      "Chorleywood",
      "Clacton on Sea",
      "Clare",
      "Coggeshall",
      "Corringham",
      "Cranfield",
      "Cromer",
      "Dereham",
      "Diss",
      "Downham Market",
      "Dunstable",
      "Ely",
      "Epping",
      "Eye",
      "Fakenham",
      "Felixstowe",
      "Flitwick",
      "Foxley",
      "Framlingham",
      "Frinton-on-Sea",
      "Gorleston on Sea",
      "Hackney",
      "Godmanchester",
      "Great Dunmow",
      "Grays",
      "Great Yarmouth",
      "Hadleigh",
      "Halesworth",
      "Halstead",
      "Harleston",
      "Harlow",
      "Harpenden",
      "Harwich",
      "Hatfield",
      "Haverhill",
      "Hemel Hempstead",
      "Hertford",
      "Hertfordshire",
      "Hingham",
      "Hitchin",
      "Hoddesdon",
      "Holt",
      "Houghton Regis",
      "Hunstanton",
      "Huntingdon",
      "Ipswich",
      "Kempston",
      "Kesgrave",
      "Kings Lynn",
      "Leighton Buzzard",
      "Leigh-on-Sea",
      "Leiston",
      "Letchworth",
      "Linslade",
      "Loddon",
      "Loughton",
      "Lowestoft",
      "Luton",
      "Maldon",
      "Manningtree",
      "March",
      "Marston Moretaine",
      "Mildenhall",
      "Needham Market",
      "Newmarket",
      "Norfolk",
      "North Walsham",
      "Norwich",
      "Orford",
      "Peterborough",
      "Potter’s Bar",
      "Ramsey",
      "Rayleigh",
      "Reepham",
      "Rickmansworth",
      "Rochford",
      "Royston",
      "Saffron Walden",
      "Sandy",
      "Sawbridgeworth",
      "Saxmundham",
      "Shefford",
      "Sheringham",
      "Soham",
      "South Ockendon",
      "South Woodham Ferrers",
      "Southend",
      "Southminster",
      "Southwold",
      "Sprowston",
      "St. Alban’s",
      "St. Neots",
      "Stalham",
      "Stanford Le Hope",
      "Stevenage",
      "Stotfold",
      "Stowmarket",
      "Sudbury",
      "Suffolk",
      "Swaffham",
      "Thaxted",
      "Thetford",
      "Thorpe St Andrew",
      "Thurrock",
      "Tring",
      "Waltham Abbey",
      "Waltham Cross",
      "Walton-on-the-Naze",
      "Watton",
      "Ware",
      "Watford",
      "Wells-next-the-Sea",
      "Welwyn Garden City",
      "West Mersea",
      "West Tilbury",
      "Whittlesey",
      "Wickford",
      "Wisbech",
      "Witham",
      "Wivenhoe",
      "Woburn",
      "Woodbridge",
    ],
  },
  {
    name: "Central England",
    id: "centralEngland",
    status: false,
    subs: ["Aylesbury"],
  },
  {
    name: "Central London",
    id: "centralLondon",
    status: false,
    subs: ["Belgravia", "Canary Wharf", "Covent Garden", "Southwark"],
  },
  {
    name: "East England",
    id: "eastEngland",
    status: false,
    subs: [
      "Acle",
      "Aldeburgh",
      "Ampthill",
      "Arlesey",
      "Attleborough",
      "Aylsham",
      "Baldock",
      "Barton-le-Clay",
      "Basildon",
      "Bedford",
      "Beccles",
      "Berkhamsted",
      "Biggleswade",
      "Billericay",
      "Bishop’s Stortford",
      "Borehamwood",
      "Brandon",
      "Braintree",
      "Brentwood",
      "Brightlingsea",
      "Bungay",
      "Buntingford",
      "Burnham-on-Crouch",
      "Bury St. Edmunds",
      "Bushey",
      "Cambridge",
      "Cambridgeshire",
      "Canvey Island",
      "Carlton Colville",
      "Chatteris",
      "Chelmsford",
      "Cheshunt",
      "Chigwell",
      "Chipping Ongar",
      "Chorleywood",
      "Clacton on Sea",
      "Clare",
      "Coggeshall",
      "Corringham",
      "Cranfield",
      "Cromer",
      "Dereham",
      "Diss",
      "Downham Market",
      "Dunstable",
      "Ely",
      "Epping",
      "Eye",
      "Fakenham",
      "Felixstowe",
      "Flitwick",
      "Foxley",
      "Framlingham",
      "Frinton-on-Sea",
      "Gorleston on Sea",
      "Hackney",
      "Godmanchester",
      "Great Dunmow",
      "Grays",
      "Great Yarmouth",
      "Hadleigh",
      "Halesworth",
      "Halstead",
      "Harleston",
      "Harlow",
      "Harpenden",
      "Harwich",
      "Hatfield",
      "Haverhill",
      "Hemel Hempstead",
      "Hertford",
      "Hertfordshire",
      "Hingham",
      "Hitchin",
      "Hoddesdon",
      "Holt",
      "Houghton Regis",
      "Hunstanton",
      "Huntingdon",
      "Ipswich",
      "Kempston",
      "Kesgrave",
      "Kings Lynn",
      "Leighton Buzzard",
      "Leigh-on-Sea",
      "Leiston",
      "Letchworth",
      "Linslade",
      "Loddon",
      "Loughton",
      "Lowestoft",
      "Luton",
      "Maldon",
      "Manningtree",
      "March",
      "Marston Moretaine",
      "Mildenhall",
      "Needham Market",
      "Newmarket",
      "Norfolk",
      "North Walsham",
      "Norwich",
      "Orford",
      "Peterborough",
      "Potter’s Bar",
      "Ramsey",
      "Rayleigh",
      "Reepham",
      "Rickmansworth",
      "Rochford",
      "Royston",
      "Saffron Walden",
      "Sandy",
      "Sawbridgeworth",
      "Saxmundham",
      "Shefford",
      "Sheringham",
      "Soham",
      "South Ockendon",
      "South Woodham Ferrers",
      "Southend",
      "Southminster",
      "Southwold",
      "Sprowston",
      "St. Alban’s",
      "St. Neots",
      "Stalham",
      "Stanford Le Hope",
      "Stevenage",
      "Stotfold",
      "Stowmarket",
      "Sudbury",
      "Suffolk",
      "Swaffham",
      "Thaxted",
      "Thetford",
      "Thorpe St Andrew",
      "Thurrock",
      "Tring",
      "Waltham Abbey",
      "Waltham Cross",
      "Walton-on-the-Naze",
      "Watton",
      "Ware",
      "Watford",
      "Wells-next-the-Sea",
      "Welwyn Garden City",
      "West Mersea",
      "West Tilbury",
      "Whittlesey",
      "Wickford",
      "Wisbech",
      "Witham",
      "Wivenhoe",
      "Woburn",
      "Woodbridge",
    ],
  },
  {
    name: "East Midlands England",
    id: "eastMidlandsEngland",
    status: false,
    subs: [
      "Alford",
      "Alfreton",
      "Arnold",
      "Ashbourne",
      "Ashby-de-la-Zouch",
      "Bakewell",
      "Batley",
      "Beeston Broxtowe",
      "Belper",
      "Bingham",
      "Bolsover",
      "Boston",
      "Bottesford",
      "Bourne",
      "Brackley",
      "Braunstone",
      "Bulwell",
      "Burgh-le-Marsh",
      "Burton Latimer",
      "Buxton",
      "Caistor",
      "Carlton",
      "Chapel-en-le-Frith",
      "Chesterfield",
      "Clay Cross",
      "Coalville",
      "Corby",
      "Cotgrave",
      "Crowland",
      "Darley Dale",
      "Daventry",
      "Derby",
      "Derbyshire",
      "Desborough",
      "Dronfield",
      "Earl Shilton",
      "Eastwood",
      "Gainsborough",
      "Glossop",
      "Grantham",
      "Heanor",
      "Harworth",
      "Higham Ferrers",
      "Hinckley",
      "Holbeach",
      "Horncastle",
      "Hucknall",
      "Ilkeston",
      "Irthlingborough",
      "Kettering",
      "Kimberley",
      "Kirkby in Ashfield",
      "Leicester",
      "Leicestershire",
      "Lincoln",
      "Lincolnshire",
      "Long Eaton",
      "Long Sutton",
      "Loughborough",
      "Louth",
      "Lutterworth",
      "Mablethorpe",
      "Man’s field",
      "Man’s field Woodhouse",
      "Market Bosworth",
      "Market Deeping",
      "Market Harborough",
      "Market Rasen",
      "Melton Mowbray",
      "Newark on Trent",
      "New Mills",
      "Northampton",
      "Northamptonshire",
      "North Hykeham",
      "Nottingham",
      "Nottinghamshire",
      "Oakham",
      "Ollerton",
      "Oundle",
      "Raunds",
      "Retford",
      "Ripley",
      "Rothwell",
      "Rushden",
      "Rutland",
      "Sandiacre",
      "Shepshed",
      "Shirebrook",
      "Skegness",
      "Sleaford",
      "Southwell",
      "Spalding",
      "Spilsby",
      "Stamford",
      "Stapleford",
      "Sutton-in-Ashfield",
      "Swadlincote",
      "Syston",
      "Towcester",
      "Uppingham",
      "Wainfleet All Saints",
      "Wellingborough",
      "West Bridgford",
      "Whaley Bridge",
      "Wigston",
      "Wirksworth",
      "Worksop",
      "Wragby",
    ],
  },
  {
    name: "North East England",
    id: "northEastEngland",
    status: false,
    subs: [
      "Alnwick",
      "Amble",
      "Ashington",
      "Barnard Castle",
      "Bedlington",
      "Berwick-upon-Tweed",
      "Billingham",
      "Bishop Auckland",
      "Blyth",
      "Chester Le Street",
      "Cleethorpes",
      "Consett",
      "Corbridge",
      "Cramlington",
      "Crook",
      "Darlington",
      "Durham",
      "Ferryhill",
      "Gateshead",
      "Greater Willington",
      "Grimsby",
      "Guisborough",
      "Haltwhistle",
      "Hartlepool",
      "Hebburn",
      "Hetton-le-Hole",
      "Hexham",
      "Houghton-le-Spring",
      "Ingleby Barwick",
      "Jarrow",
      "Killingworth",
      "Loftus",
      "Longbenton",
      "Middlesbrough",
      "Morpeth",
      "Newbiggin-by-the-Sea",
      "Newcastle",
      "Newton Aycliffe",
      "Peterlee",
      "Ponteland",
      "Prudhoe",
      "Redcar",
      "Rothbury",
      "Seaham",
      "Saltburn-by-the-Sea",
      "Sedgefield",
      "Shildon",
      "Skelton",
      "South Shields",
      "Spennymoor",
      "Stanhope",
      "Stanley",
      "Stockton on Tees",
      "Sunderland",
      "Thornaby on Tees",
      "Tow Law",
      "Tyne and Wear",
      "Tynemouth",
      "Wallsend",
      "Washington",
      "West Bedlington",
      "Whitley Bay",
      "Wolsingham",
      "Wooler",
      "Yarm",
      "York",
    ],
  },
  {
    name: "North England",
    id: "northEngland",
    status: false,
    subs: [
      "Adwick Le Street",
      "Askern",
      "Barnsley",
      "Barton-upon-Humber",
      "Bawtry",
      "Bentham",
      "Bentley",
      "Beverley",
      "Bingley",
      "Boroughbridge",
      "Bridlington",
      "Brigg",
      "Brough",
      "Calderdale",
      "Chapeltown",
      "Cleckheaton",
      "Colburn",
      "Conisbrough",
      "Crowle",
      "Denholme",
      "Dinnington",
      "Doncaster",
      "Driffield",
      "Easingwold",
      "East Yorkshire",
      "Elland",
      "Epworth",
      "Featherstone",
      "Filey",
      "Goole",
      "Grassington",
      "Harrogate",
      "Hawes",
      "Haworth",
      "Haxby",
      "Hebden Bridge",
      "Hebden Royd",
      "Hedon",
      "Helmsley",
      "Hemsworth",
      "Hessle",
      "Hetton",
      "Hornsea",
      "Howden",
      "Hoyland",
      "Hull",
      "Ilkley",
      "Immingham",
      "Kingston Upon Hull",
      "Kirkbymoorside",
      "Kirton-in-Lindsey",
      "Knaresborough",
      "Knottingley",
      "Leyburn",
      "Lofthouse",
      "Maltby",
      "Malton",
      "Market Weighton",
      "Masham",
      "Meltham",
      "Mexborough",
      "Middleham",
      "North Yorkshire",
      "Northallerton",
      "Norton-on-Derwent",
      "Otley",
      "Outwood",
      "Pateley Bridge",
      "Penistone",
      "Pickering",
      "Pocklington",
      "Rawmarsh",
      "Ripon",
      "Rotherham",
      "Scarborough",
      "Scunthorpe",
      "Selby",
      "Settle",
      "Sheffield",
      "Silsden",
      "Skipton",
      "Snaith",
      "South Cave",
      "South Elmsall",
      "South Kirkby",
      "South Yorkshire",
      "Stainforth",
      "Stocksbridge",
      "Tadcaster",
      "Thirsk",
      "Thorne",
      "Tickhill",
      "Todmorden",
      "Wath Upon Dearne",
      "West Yorkshire",
      "Wetherby",
      "Whitby",
      "Winterton",
      "Withernsea",
      "Wombwell",
    ],
  },
  {
    name: "North London",
    id: "northLondon",
    status: false,
    subs: [
      "Barnet",
      "Edgware",
      "Edmonton",
      "Enfield",
      "Finchley",
      "Hendon",
      "Hornsey",
      "Southgate",
      "Tottenham",
      "Wood Green",
    ],
  },
  {
    name: "North West England",
    id: "northWestEngland",
    status: false,
    subs: [
      "Accrington",
      "Adlington",
      "Alsager",
      "Alston",
      "Altrincham",
      "Ambleside",
      "Appleby-in-Westmorland",
      "Ashton in Makerfield",
      "Ashton under Lyne",
      "Atherton",
      "Aspatria",
      "Bacup",
      "Bamber Bridge",
      "Barnoldswick",
      "Barrow in Furness",
      "Bebington",
      "Birchwood",
      "Birkenhead",
      "Blackburn",
      "Blackpool",
      "Blackrod",
      "Bollington",
      "Bolton",
      "Bootle",
      "Bramhall",
      "Brampton",
      "Brierfield",
      "Bromborough",
      "Broughton",
      "Burnley",
      "Bury",
      "Carlisle",
      "Carnforth",
      "Chadderton",
      "Cheadle Hulme",
      "Chester",
      "Chorley",
      "Cleator Moor",
      "Cleveleys",
      "Clitheroe",
      "Cockermouth",
      "Colne",
      "Congleton",
      "Crewe",
      "Crosby",
      "Cumbria",
      "Dalton-in-Furness",
      "Darwen",
      "Denton",
      "Droylsden",
      "Dukinfield",
      "Earby",
      "Eccles",
      "Egremont",
      "Ellesmere Port",
      "Failsworth",
      "Farnworth",
      "Fleetwood",
      "Formby",
      "Frodsham",
      "Fulwood",
      "Garstang",
      "Gatley",
      "Golborne",
      "Grange-over-Sands",
      "Halton",
      "Haslingden",
      "Hazel Grove",
      "Heswall",
      "Heywood",
      "Hindley",
      "Horwich",
      "Hoylake",
      "Hyde",
      "Irlam",
      "Kendal",
      "Keswick",
      "Kirkby",
      "Kirkby Lonsdale",
      "Kirkby Stephen",
      "Kirkham",
      "Knutsford",
      "Lancashire",
      "Lancaster",
      "Leigh",
      "Leyland",
      "Litherland",
      "Liverpool",
      "Longridge",
      "Longtown",
      "Lytham St Annes",
      "Macclesfield",
      "Maghull",
      "Manchester",
      "Marple",
      "Maryport",
      "Medlar-with-Wesham",
      "Merseyside",
      "Middleton",
      "Middlewich",
      "Millom",
      "Morecambe",
      "Mossley",
      "Nantwich",
      "Nelson",
      "Neston",
      "Newton Le Willows",
      "Northwich",
      "Oldham",
      "Ormskirk",
      "Padiham",
      "Partington",
      "Penrith",
      "Penwortham",
      "Poulton Le Fylde",
      "Poynton-with-Worth",
      "Preesall",
      "Prescot",
      "Preston",
      "Radcliffe",
      "Ramsbottom",
      "Rawtenstall",
      "Rochdale",
      "Romiley",
      "Royton",
      "Runcorn",
      "Salford",
      "Sandbach",
      "Sedbergh",
      "Shaw",
      "Silloth",
      "Skelmersdale",
      "Southport",
      "St. Helens",
      "Staveley",
      "Stalybridge",
      "Stockport",
      "Stretford",
      "Swinton",
      "Trafford",
      "Tameside",
      "Ulverston",
      "Urmston",
      "Walkden",
      "Wallasey",
      "Warrington",
      "Westhoughton",
      "West Kirby",
      "Whiston",
      "Whitefield",
      "Whitehaven",
      "Whitworth",
      "Widnes",
      "Wigan",
      "Wigton",
      "Wilmslow",
      "Windermere",
      "Winsford",
      "Wirral",
      "Workington",
    ],
  },
  {
    name: "North West London",
    id: "northWestLondon",
    status: false,
    subs: [
      "Brent",
      "Camden",
      "Harrow",
      "Pinner",
      "Ruislip",
      "Stanmore",
      "Wembley",
      "Willesden",
    ],
  },
  {
    name: "South East England",
    id: "southEastEngland",
    status: false,
    subs: [
      "Abdingon-on-Thames",
      "Acton",
      "Aldershot",
      "Alton",
      "Amersham",
      "Andover",
      "Angel",
      "Arundel",
      "Ashford",
      "Balham",
      "Bampton",
      "Banbury",
      "Basingstoke",
      "Battersea",
      "Battle",
      "Beaconsfield",
      "Bexhill",
      "Bicester",
      "Bishop’s Waltham",
      "Bletchley",
      "Bognor Regis",
      "Bordon",
      "Bracknell",
      "Brading",
      "Bray",
      "Brighton",
      "Broadstairs",
      "Bromley",
      "Buckingham",
      "Buckinghamshire",
      "Burford",
      "Burgess Hill",
      "Camberley",
      "Canterbury",
      "Carterton",
      "Caterham",
      "Chalfont St. Giles",
      "Charlbury",
      "Chatham",
      "Chelsea",
      "Chesham",
      "Chertsey",
      "Chichester",
      "Chilton",
      "Chipping Norton",
      "Chiswick",
      "Clapham",
      "Cobham",
      "Colchester",
      "Cowes",
      "Crawley",
      "Cranbrook",
      "Crowborough",
      "Crowthorne",
      "Cuckfield",
      "Dartford",
      "Deal",
      "Didcot",
      "Ditton",
      "Dorking",
      "Dover",
      "Dulwich",
      "Ealing",
      "Earley",
      "East Cowes",
      "East Grinstead",
      "East Sussex",
      "Eastbourne",
      "Eastleigh",
      "Edenbridge",
      "Egham",
      "Emsworth",
      "Epsom",
      "Esher",
      "Essex",
      "Eton",
      "Ewell",
      "Fareham",
      "Faringdon",
      "Farnborough",
      "Farnham",
      "Faversham",
      "Fenny Stratford",
      "Fleet",
      "Folkestone",
      "Fordingbridge",
      "Freshwater",
      "Frimley",
      "Fulham",
      "Gerrard’s Cross",
      "Gillingham",
      "Godalming",
      "Gosport",
      "Gravesend",
      "Greehithe",
      "Guildford",
      "Hammersmith",
      "Hampshire",
      "Hailsham",
      "Haslemere",
      "Hastings",
      "Havant",
      "Hawkinge",
      "Hawley",
      "Haywards Heath",
      "Heathfield",
      "Hedge End",
      "Henley-on-Thames",
      "Herne Bay",
      "High Wycombe",
      "Horley",
      "Horndean",
      "Horsham",
      "Hounslow",
      "Hungerford",
      "Hythe",
      "Isle of Wight",
      "Islington",
      "Kent",
      "Leatherhead",
      "Lewes",
      "Lewisham",
      "Littlehampton",
      "London",
      "Lydd",
      "Lymington",
      "Maidenhead",
      "Maidstone",
      "Margate",
      "Marlow",
      "Medway",
      "Midhurst",
      "Milton Keynes",
      "Minster",
      "Minster Swale",
      "New Addington",
      "New Alresford",
      "New Milton",
      "New Romney",
      "Newbury",
      "Newhaven",
      "Northfleet",
      "Olney",
      "Oxford",
      "Oxfordshire",
      "Paddock Wood",
      "Peacehaven",
      "Petersfield",
      "Petworth",
      "Polegate",
      "Portslade By Sea",
      "Portsmouth",
      "Princes Risborough",
      "Queenborough",
      "Ramsgate",
      "Redhill",
      "Reigate",
      "Richmond",
      "Ringwood",
      "Rochester",
      "Romsey",
      "Ryde",
      "Rye",
      "Sale",
      "Sandown",
      "Sandhurst",
      "Sandwich",
      "Seaford",
      "Selsey",
      "Sevenoaks",
      "Shanklin",
      "Shoreham-by-Sea",
      "Sittingbourne",
      "Slough",
      "Southall",
      "Staines",
      "Streatham",
      "Sheerness",
      "Snodland",
      "Southborough",
      "Stubbington",
      "Southsea",
      "Southwick",
      "Steyning",
      "Stoke Poges",
      "Stony Stratford",
      "Strood",
      "Surbiton",
      "Surrey",
      "Sutton",
      "Swanley",
      "Swanscombe",
      "Tadley",
      "Telscombe",
      "Tenterden",
      "Thame",
      "Thanet",
      "Thatcham",
      "Thong",
      "Tonbridge",
      "Tooting",
      "Totton",
      "Tunbridge Wells",
      "Twickenham",
      "Uckfield",
      "Ventnor",
      "Walton-on-Thames",
      "Wadhurst",
      "Wallingford",
      "Walmer",
      "Wantage",
      "Watlington",
      "Wealden",
      "Wendover",
      "West Berkshire",
      "West Malling",
      "Westerham",
      "Westminster",
      "Weybridge",
      "Whitstable",
      "Wickham",
      "Wimbledon",
      "Winchelsea",
      "Winchester",
      "Windsor",
      "Winslow",
      "Witney",
      "Woking",
      "Wokingham",
      "Wolverton",
      "Woodley",
      "Woodstock",
      "Worthing",
      "Yateley",
    ],
  },
  {
    name: "South East London",
    id: "southEastLondon",
    status: false,
    subs: [
      "Beckenham",
      "Bedale",
      "Bexley",
      "Blackheath",
      "Crayford",
      "Erith",
      "Greenwich",
      "Orpington",
      "Sidcup",
      "St Mary Cray",
      "Woolwich",
    ],
  },
  {
    name: "South England",
    id: "southEngland",
    status: false,
    subs: [
      "Abingdon",
      "Bishop’s Waltham",
      "Croydon",
      "Hove",
      "Reading",
      "Southampton",
      "Weymouth",
    ],
  },
  {
    name: "South London",
    id: "southLondon",
    status: false,
    subs: [
      "Brixton",
      "Carshalton",
      "Coulsdon",
      "Lambeth",
      "Mitcham",
      "Morden",
      "Purley",
      "Wallington",
    ],
  },
  {
    name: "South West England",
    id: "southWestEngland",
    status: false,
    subs: [
      "Amesbury",
      "Ashburton",
      "Axbridge",
      "Barnstaple",
      "Bath",
      "Beaminster",
      "Berkeley",
      "Bideford",
      "Blandford Forum",
      "Bishop’s Castle",
      "Bodmin",
      "Bournemouth",
      "Bovey Tracey",
      "Bradley Stoke",
      "Bradninch",
      "Bridgwater",
      "Bridport",
      "Bristol",
      "Brixham",
      "Bruton",
      "Bude",
      "Budleigh Salterton",
      "Burnham-on-Sea",
      "Callington",
      "Calne",
      "Camborne",
      "Castle Cary",
      "Chagford",
      "Chard",
      "Cheltenham",
      "Chickerell",
      "Chippenham",
      "Chipping Campden",
      "Chipping Sodbury",
      "Christchurch",
      "Chudleigh",
      "Clevedon",
      "Clifton",
      "Coleford",
      "Cinderford",
      "Cirencester",
      "Colyton",
      "Cornwall",
      "Corsham",
      "Crediton",
      "Crewkerne",
      "Cricklade",
      "Cullompton",
      "Dartmouth",
      "Dawlish",
      "Devizes",
      "Devon",
      "Dorchester",
      "Dorset",
      "Dulverton",
      "Dunster",
      "Dursley",
      "Exeter",
      "Exmouth",
      "Fairford",
      "Falmouth",
      "Ferndown",
      "Filtron",
      "Fowey",
      "Frome",
      "Glastonbury",
      "Gloucester",
      "Gloucestershire",
      "Great Torrington",
      "Hartland",
      "Hatherleigh",
      "Hayle",
      "Helston",
      "Highbridge",
      "Highworth",
      "Holsworthy",
      "Hugh Town",
      "Ilchester",
      "Ilfracombe",
      "Ilminster",
      "Ivybridge",
      "Keynsham",
      "Kingsbridge",
      "Kingsteignton",
      "Langport",
      "Launceston",
      "Lechlade",
      "Liskeard",
      "Looe",
      "Lostwithiel",
      "Ludgershall",
      "Lydney",
      "Lyme Regis",
      "Lynton",
      "Lytchett Minster",
      "Malmesbury",
      "Marazion",
      "Marlborough",
      "Melksham",
      "Mere",
      "Midsomer Norton",
      "Minchinhampton",
      "Minehead",
      "Mitcheldean",
      "Modbury",
      "Moreton-in-Marsh",
      "Moretonhampstead",
      "Nailsea",
      "Nailsworth",
      "Newent",
      "Newlyn",
      "Newquay",
      "Newton Abbot",
      "North Petherton",
      "North Tawton",
      "Northam",
      "Northleach",
      "Norton Radstock",
      "Okehampton",
      "Ottery St Mary",
      "Padstow",
      "Paignton",
      "Painswick",
      "Patchway",
      "Penryn",
      "Penzance",
      "Plymouth",
      "Plympton",
      "Plymstock",
      "Poltimore",
      "Poole",
      "Porthleven",
      "Portishead",
      "Portland",
      "Quedgeley",
      "Quintrell Downs",
      "Redruth",
      "Royal Wootton Bassett",
      "Salcombe",
      "Salisbury",
      "Seaton",
      "Shaftesbury",
      "Shepton Mallet",
      "Sherborne",
      "Sidmouth",
      "Somerset",
      "Somerton",
      "South Brent",
      "South Molton",
      "St. Austell",
      "St. Blaise",
      "St. Blazey",
      "St. Columb Major",
      "St. Ives",
      "St. Just-in-Penwith",
      "Stalbridge",
      "Stonehouse",
      "Stow-on-the-Wold",
      "Stroud",
      "Sturminster Newton",
      "Swanage",
      "Swindon",
      "Taunton",
      "Tavistock",
      "Teignmouth",
      "Tewkesbury",
      "Thornbury",
      "Tidworth",
      "Tiverton",
      "Topsham",
      "Torpoint",
      "Torquay",
      "Totnes",
      "Trowbridge",
      "Truro",
      "Verwood",
      "Wadebridge",
      "Wareham",
      "Warminster",
      "Watchet",
      "Wellington",
      "Wells",
      "Westbury",
      "Weston-Super-Mare",
      "Weymouth",
      "Wickwar",
      "Wilton",
      "Wiltshire",
      "Wimborne Minster",
      "Wincanton",
      "Winchcombe",
      "Wiveliscombe",
      "Wotton-under-Edge",
      "Yate",
      "Yeovil",
    ],
  },
  {
    name: "South West London",
    id: "southWestLondon",
    status: false,
    subs: [
      "Barnes",
      "Chessington",
      "Hampton",
      "Kingston-upon-Thames",
      "Teddington",
      "Wandsworth",
    ],
  },
  {
    name: "West London",
    id: "westLondon",
    status: false,
    subs: [
      "Brentford",
      "Feltham",
      "Greenford",
      "Hayes",
      "Isleworth",
      "Northolt",
      "Uxbridge",
      "West Drayton",
    ],
  },
  {
    name: "West MidLands England",
    id: "westMidLandsEngland",
    status: false,
    subs: [
      "Alcester",
      "Aldridge",
      "Atherstone",
      "Barnt Green",
      "Bedworth",
      "Bewdley",
      "Biddulph",
      "Bilston",
      "Birmingham",
      "Bishop’s Castle",
      "Bloxwich",
      "Bridgnorth",
      "Brierley Hill",
      "Bromsgrove",
      "Bromyard",
      "Broseley",
      "Brownhills",
      "Burntwood",
      "Burslem",
      "Burton",
      "Cannock",
      "Church Stretton",
      "Cleobury Mortimer",
      "Clun",
      "Coleshill",
      "Coseley",
      "Coventry",
      "Craven Arms",
      "Darlaston",
      "Dawley",
      "Droitwich",
      "Dudley",
      "Ellesmere",
      "Evesham",
      "Fazeley",
      "Fordbridge",
      "Great Malvern",
      "Great Wyrley",
      "Hednesford",
      "Halesowen",
      "Hereford",
      "Kenilworth",
      "Kidderminster",
      "Kidsgrove",
      "Kingswinford",
      "Kington",
      "Ledbury",
      "Leek",
      "Leominster",
      "Lichfield",
      "Ludlow",
      "Madeley",
      "Malvern Hills",
      "Market Drayton",
      "Much Wenlock",
      "Newcastle Under Lyme",
      "Nuneaton",
      "Oakengates",
      "Oldbury",
      "Oswestry",
      "Penkridge",
      "Pershore",
      "Redditch",
      "Ross-on-Wye",
      "Rowley Regis",
      "Royal Leamington Spa",
      "Rugby",
      "Rugeley",
      "Sandwell",
      "Sedgley",
      "Shifnal",
      "Shipston-on-Stour",
      "Shrewsbury",
      "Smethwick",
      "Solihull",
      "Stafford",
      "Staffordshire",
      "Stoke on Trent",
      "Stone",
      "Stourbridge",
      "Stourport on Severn",
      "Stratford upon Avon",
      "Sutton Coldfield",
      "Tamworth",
      "Telford",
      "Tenbury Wells",
      "Tipton",
      "Upton-upon-Severn",
      "Uttoxeter",
      "Walsall",
      "Warwick",
      "Warwickshire",
      "Wednesbury",
      "West Bromwich",
      "Whitchurch",
      "Whitnash",
      "Willenhall",
      "Wolverhampton",
      "Worcester",
      "Worcestershire",
      "Yoxall",
    ],
  },
  {
    name: "West YorkShire England",
    id: "westYorkShireEngland",
    status: false,
    subs: [
        "Bradford", "Brighouse", "Castleford", "Dewsbury", 
        "Halifax", "Holmfirth", "Horsforth", "Huddersfield", 
        "Keighley", "Leeds", "Liversedge", "Mirfield", 
        "Morley", "Normanton", "Ossett", "Pontefract", 
        "Pudsey", "Shipley", "Thornton", "Wakefield", 
        "Yeadon"
    ],
  },
];
